# Generated by Django 4.2.11 on 2024-05-06 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_category_options_category_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='product.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='top_level_comment_id',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
    ]
