# Generated by Django 4.2.11 on 2024-05-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_comment_parent_alter_comment_top_level_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='top_level_comment_id',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True),
        ),
    ]
