# Generated by Django 4.2.11 on 2024-05-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_cartitem_amount_cartitem_discount_order_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='name',
            field=models.CharField(max_length=8),
        ),
    ]
